#
# Exercise #1
# Create N nodes and elects a master
#

VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
#ENV['VAGRANT_NO_PARALLEL'] = "1"
ENV['FORWARD_DOCKER_PORTS'] = "1"
ENV['VAGRANT_EXPERIMENTAL']="typed_triggers"

unless Vagrant.has_plugin?("vagrant-docker-compose")
  system("vagrant plugin install vagrant-docker-compose")
  puts "Dependencies installed, please try the command again."
  exit
end

# Names of Docker images built:
KEEPER_IMAGE  = "ds/cv04/keeper:0.1"
MQTT_IMAGE    = "ds/cv04/mqtt:0.1"
CLIENT_IMAGE  = "ds/cv04/client:0.1"

# Subnet to use:
SUBNET = "10.0.1."

# Definition of clusters
BROKER_CLUSTER_NAME = "mybrokercluster"

# Configure the individual types of nodes
KEEPER = {:nameprefix => "keeper-",
          :subnet => SUBNET,
          :ip_offset => 10,
          :image => KEEPER_IMAGE}

MQTT  = {:nameprefix => "mqtt-",
         :subnet => SUBNET,
         :ip_offset => 20,
         :image => MQTT_IMAGE,
}

CLIENT = {:nameprefix => "client-",
          :subnet => SUBNET,
          :ip_offset => 30,
          :image => CLIENT_IMAGE,
          :config => "client/client.cfg"
}

# Configure number of nodes in the system
KEEPERS_COUNT = 3
MQTTS_COUNT = 3
CLIENTS_COUNT = 3

keeper_hosts = ""
keeper_client_hosts = ""

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.trigger.before :up, type: :command do |trigger|
    trigger.name = "Build docker images and configuration files"
    trigger.ruby do |env, machine|
        # --- start of Ruby script ---
        # Build Zoonode list:
        puts "Building keeper configuration."
        zoo_ensemble = []
        zoo_hosts = []
        (1..KEEPERS_COUNT).each do |i|
            zoo_ensemble << "server.#{i}=#{KEEPER[:subnet]}#{KEEPER[:ip_offset] + i}:2888:3888;2181"
            zoo_hosts << "#{KEEPER[:subnet]}#{KEEPER[:ip_offset] + i}:2181"
        end
        keeper_hosts = zoo_ensemble.join(" ")
        keeper_client_hosts = zoo_hosts.join(",")
        # Build Keeper node image:
        puts "Building keeper image:"
        `docker build keeper -t "#{KEEPER_IMAGE}"`
        # Build mqtt node image:
        puts "Building MQTT node image:"
        `docker build broker -t "#{MQTT_IMAGE}"`
        # Build client node image:
        puts "Building client node image:"
        `docker build client -t "#{CLIENT_IMAGE}"`
    end
  end
  config.ssh.insert_key = false

  # Keeper definitions
  (1..KEEPERS_COUNT).each do |i|
    node_ip_addr = "#{KEEPER[:subnet]}#{KEEPER[:ip_offset] + i}"
    node_name = "#{KEEPER[:nameprefix]}#{i}"
    # Definition of Keeper
    config.vm.define node_name do |s|
      s.vm.network "private_network", ip: node_ip_addr
      s.vm.hostname = node_name
      s.vm.provider "docker" do |d|
        d.image = KEEPER[:image]
        d.name = node_name
        d.has_ssh = true
        d.env = { "KEEPER_ID" => i, "KEEPER_HOSTS" => "#{keeper_hosts}" }
      end
      s.vm.post_up_message = "Node #{node_name} up and running. You can access the node with 'vagrant ssh #{node_name}'}"
    end
  end

  # MQTT broker definitions
  (1..MQTTS_COUNT).each do |i|
    node_ip_addr = "#{MQTT[:subnet]}#{MQTT[:ip_offset] + i}"
    node_name = "#{MQTT[:nameprefix]}#{i}"
    # Definition of client node
    config.vm.define node_name do |s|
      s.vm.network "private_network", ip: node_ip_addr
      s.vm.hostname = node_name
      s.vm.provider "docker" do |d|
        d.image = MQTT[:image]
        d.name = node_name
        d.has_ssh = true
        d.env = { "KEEPER_HOSTS" => "#{keeper_client_hosts}", "IP" => "#{node_ip_addr}", "CLUSTER_NAME" => "#{BROKER_CLUSTER_NAME}" }
      end
      s.vm.post_up_message = "Node #{node_name} up and running. You can access the node with 'vagrant ssh #{node_name}'}"
    end
  end

  # Client node definitions
  (1..CLIENTS_COUNT).each do |i|
    node_ip_addr = "#{CLIENT[:subnet]}#{CLIENT[:ip_offset] + i}"
    node_name = "#{CLIENT[:nameprefix]}#{i}"
    # Definition of client node
    config.vm.define node_name do |s|
      s.vm.network "private_network", ip: node_ip_addr
      s.vm.hostname = node_name
      s.vm.provider "docker" do |d|
        d.image = CLIENT[:image]
        d.name = node_name
        d.has_ssh = true
        d.env = { "KEEPER_HOSTS" => "#{keeper_client_hosts}", "CLUSTER_NAME" => "#{BROKER_CLUSTER_NAME}" }
      end
      s.vm.post_up_message = "Node #{node_name} up and running. You can access the node with 'vagrant ssh #{node_name}'}"
    end
  end

end

# EOF
